services:
  rails:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    command: ./bin/rails server -b 0.0.0.0
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    volumes:
      - ./log:/rails/log
      - ./tmp:/rails/tmp
      - .:/rails
    env_file:
      - .env
    tty: true
    stdin_open: true
    networks:
      - postgres_network
      - kafka_network

networks:
  postgres_network:
    name: postgres_network
    external: true
    driver: bridge
  kafka_network:
    name: kafka_network
    external: true
    driver: bridge
